#!/bin/sh

echo "DB host: $FLYWAY_PLACEHOLDERS_DBHOST, db name: $FLYWAY_PLACEHOLDERS_DBNAME, user: $FLYWAY_USER"
PGPASSWORD=$FLYWAY_PASSWORD psql \
  -h $FLYWAY_PLACEHOLDERS_DBHOST \
  -d $FLYWAY_PLACEHOLDERS_DBNAME \
  -U $FLYWAY_USER \
  -c "\copy cpu_usage from '${FLYWAY_PLACEHOLDERS_MIGRATIONSROOTPATH}/data/cpu_usage.csv' csv header;"